apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      version: 1.0.1
  interval: 1h0m0s
  releaseName: nginx-ingress-controller
  targetNamespace: default
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    controller:
      enableCustomResources: true
      hostPort:
        enable: true
      nodeSelector:
        ingress-ready: "true"
      service:
        type: NodePort
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Equal
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Equal
          effect: NoSchedule
